# Generated by Django 2.2 on 2021-08-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='file_field',
        ),
        migrations.CreateModel(
            name='FileForBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='img/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_blog.Blog')),
            ],
        ),
    ]
