# Generated by Django 2.2 on 2021-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20210830_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='anon.jpg', null=True, upload_to='avatars/'),
        ),
    ]
