# Generated by Django 2.2 on 2021-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_auto_20210830_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default=None, upload_to='avatars/'),
        ),
    ]
