# Generated by Django 2.2 on 2021-08-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_auto_20210831_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default=None, null=True, upload_to='avatars/'),
        ),
    ]
