# Generated by Django 2.2 on 2021-08-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_profile_avatar_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_2',
        ),
    ]
