# Generated by Django 2.2 on 2021-08-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
        migrations.AlterModelTable(
            name='advertisementauthor',
            table='advertisementauthor',
        ),
    ]
