# Generated by Django 2.2 on 2021-08-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_auto_20210815_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'advertisement_chapter',
            },
        ),
        migrations.AlterModelTable(
            name='advertisementauthor',
            table='advertisement_author',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='chapter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='advertisements_app.AdvertisementChapter'),
        ),
    ]
