# Generated by Django 2.2 on 2021-08-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0003_auto_20210815_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('count_of_employers', models.IntegerField()),
                ('director', models.CharField(max_length=30)),
                ('chef', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house', models.IntegerField()),
                ('serves_hot_dogs', models.BooleanField(default=False)),
                ('serves_pizza', models.BooleanField(default=False)),
                ('serves_sushi', models.BooleanField(default=False)),
                ('serves_burgers', models.BooleanField(default=False)),
                ('serves_donats', models.BooleanField(default=False)),
                ('serves_coffee', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house', models.IntegerField()),
                ('apartment', models.IntegerField()),
                ('seniority', models.TextField()),
                ('education', models.TextField(max_length=50)),
                ('cources', models.TextField(max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.Restaurant')),
            ],
        ),
    ]
