# Generated by Django 2.2 on 2021-08-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_permissions', '0003_resume'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancy',
            table='Vacancy',
        ),
    ]
