# Generated by Django 3.2.6 on 2021-08-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20210812_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(db_index=True, max_length=1500, verbose_name='название объявление'),
        ),
    ]
