# Generated by Django 3.2.6 on 2021-08-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisement_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
