# Generated by Django 3.2.6 on 2021-08-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
