# Generated by Django 2.2 on 2021-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20210825_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Верификация'),
        ),
    ]
